title: Kit chooser
hero_image: images/banner.png
description: default-project-template description
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: What you will make
  - title: Creating your kit
  - title: Adding decoration
  - title: Choosing all the colours!
  - title: Challange